name: Update Helm Chart

on:
  push:
    branches: [ main ]

jobs:
  update-helm:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout Helm repo
    - name: Checkout Helm Repo
      uses: actions/checkout@v3
      with:
        repository: RAVIKUMAR-DEKKA/html-app-helm
        token: ${{ secrets.GIT_TOKEN }}

    # 2️⃣ Update image tag in values.yaml
    - name: Update image tag
      run: |
        sed -i "s/tag:.*/tag: \"${{ github.sha }}\"/" values.yaml

    # 3️⃣ Commit and push changes
    - name: Commit & Push
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add values.yaml
        git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
        git push
